#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
RUNTIME_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd -P)
PYTHON_HOME="$RUNTIME_ROOT/Python.framework/Versions/Current"

unset PYTHONPATH PYTHONHOME PYTHONSTARTUP PYTHONINSPECT PYTHONBREAKPOINT
unset DYLD_LIBRARY_PATH DYLD_FRAMEWORK_PATH DYLD_INSERT_LIBRARIES
unset LD_LIBRARY_PATH
export PYTHONHOME="$PYTHON_HOME"
export PYTHONPATH="$RUNTIME_ROOT/site-packages"
export PYTHONNOUSERSITE=1
export PYTHONDONTWRITEBYTECODE=1
export PIP_NO_CACHE_DIR=1

exec "$PYTHON_HOME/bin/python3" "$@"
