#!/usr/bin/env python3
"""Create a hashed requirements lock from exact specs and downloaded wheels."""

from __future__ import annotations

import argparse
import hashlib
import re
import zipfile
from email.parser import BytesParser
from pathlib import Path
from typing import Dict, List, Tuple


def canonical_name(value: str) -> str:
    return re.sub(r"[-_.]+", "-", value).lower()


def read_specs(path: Path) -> Dict[str, Tuple[str, str]]:
    specs: Dict[str, Tuple[str, str]] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "==" not in line:
            raise ValueError("requirement is not exact: {}".format(line))
        name, version = line.split("==", 1)
        key = canonical_name(name)
        if key in specs:
            raise ValueError("duplicate requirement: {}".format(name))
        specs[key] = (key, version)
    return specs


def wheel_identity(path: Path) -> Tuple[str, str]:
    with zipfile.ZipFile(path) as archive:
        metadata_names = [
            name
            for name in archive.namelist()
            if name.endswith(".dist-info/METADATA") and name.count("/") == 1
        ]
        if len(metadata_names) != 1:
            raise ValueError("wheel has ambiguous metadata: {}".format(path.name))
        metadata = BytesParser().parsebytes(archive.read(metadata_names[0]))
    return canonical_name(metadata["Name"]), metadata["Version"]


def render_lock(specs_path: Path | None, wheelhouse: Path) -> str:
    specs = read_specs(specs_path) if specs_path is not None else {}
    hashes: Dict[Tuple[str, str], List[str]] = {}
    for wheel in sorted(wheelhouse.glob("*.whl")):
        identity = wheel_identity(wheel)
        digest = hashlib.sha256(wheel.read_bytes()).hexdigest()
        hashes.setdefault(identity, []).append(digest)

    if specs:
        unexpected = sorted(identity for identity in hashes if identity[0] not in specs)
        if unexpected:
            raise ValueError("unexpected wheels: {}".format(unexpected))
    else:
        for name, version in hashes:
            existing = specs.get(name)
            if existing is not None and existing[1] != version:
                raise ValueError("multiple resolved versions for {}".format(name))
            specs[name] = (name, version)

    lines = [
        "# Generated by Scripts/update_runtime_lock.sh.",
        "# Target is defined by Runtime/runtime-policy.json. Do not edit by hand.",
    ]
    for key in sorted(specs):
        name, version = specs[key]
        artifacts = sorted(hashes.get((key, version), []))
        if not artifacts:
            raise ValueError("missing wheel for {}=={}".format(name, version))
        lines.append("{}=={} \\".format(name, version))
        for index, digest in enumerate(artifacts):
            suffix = " \\" if index < len(artifacts) - 1 else ""
            lines.append("    --hash=sha256:{}{}".format(digest, suffix))
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--specs", type=Path)
    parser.add_argument("--wheelhouse", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    content = render_lock(args.specs, args.wheelhouse)
    temporary = args.output.with_suffix(args.output.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
